<?php
/**
 * Created by PhpStorm.
 * User: sfdev
 * Date: 23.02.18
 * Time: 0:00
 */

namespace Training\Test\Controller\Index;


class Index extends \Magento\Framework\App\Action\Action
{
    public function execute() {
        //added url rewrite by query
        /*
          INSERT INTO url_rewrite SET request_path="testpage.html", target_path="test/index/index", entity_type="custom", entity_id=1,   redirect_type=«0», store_id=1, is_autogenerated=0;
         */

     //   $this->getResponse()->appendBody("HELLO WORLD");
        $this->_redirect('catalog/category/view/id/3');
    }
}